### ISSUE TITLE
Feedback: Project Proposal

### ISSUE THREAD

**Issue by s-pangburn** [jbrettk629/sailbnb#1]
Looks good Brett! 🙂 Here's my feedback:

## Homepage
- [x] You have a dead "Routes" link that doesn't go anywhere

## MVP List 
- [x] Well done! The only thing that needs to be fixed is the formatting. [Make sure it looks like Bluebird!](https://github.com/appacademy/bluebird/wiki/mvp-list)

## Schema
- [x] Having the word "Schema" at the top in plaintext looks a little weird.
- [x] Include your `belongs_to` and `has_many` associations!! (with backtick formatting and everything!)

## Sample State
- [x] Again, having Sample State at the top in 12pt. font is a little weird.
- [x] First half of your sample state isn't in the box? 😄 (the bottom isn't either, it looks like)
- [x] Put ```js at the top of your code block in Markdown to enable syntax highlighting!
- [x] Include slices of state for bookings and reviews. If you are confused on how to do this, take another look at [this reading](https://redux.js.org/recipes/structuringreducers/normalizingstateshape) on normalizing state shape from earlier in the curriculum, and [look at how Bluebird does it as well](https://github.com/appacademy/bluebird/wiki/sample-state).

## Frontend Routes
- [x] Again, formatting. Look at Bluebird!
- [x] Remove the plaintext title

## Backend Routes
- [x] Formatting!!

Let me know if you have any questions!

**Comment by jbrettk629** [comment]
Stephen, I fixed the issues, how is it now?

**Comment by s-pangburn** [comment]
👍
